### ISSUE TITLE
Conceptual Data Model 

### ISSUE THREAD

**Issue by DavidLeDuy** [DavidLeDuy/ProperProperties#1]
Only in Chen-Notation

https://creately.com/diagram/kbavnxng1/wDnBlFAeR8pjKGSO9RkUZ36I4NA%3D

**Comment by Saliit00** [comment]
Updated High-Level ERM:
https://creately.com/diagram/kbro3tyy1/T1dNLE5G8xRYPT1L0mU3mwy7tgU%3D
