### ISSUE TITLE
List of all relevant entities and relationships

### ISSUE THREAD

**Issue by DavidLeDuy** [DavidLeDuy/ProperProperties#3]
Categorized into each user view

Tenant in our Case

**Comment by AK-1995** [comment]
TenantView relationship von Ekrem und mir.

[TenantView_Relationships.xlsx](https://github.com/DavidLeDuy/ProperProperties/files/4781455/TenantView_Relationships.xlsx)

**Comment by DavidLeDuy** [comment]
Seid ihr sicher das passt? Ich würde _user view_ als view im Sinne von Datenbanken _view_ sehen. Also als eine virtuelle Tabelle mit den Informationen die der jeweilige _user_ braucht.
