### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TheDevMann** [DavidLeDuy/ProperProperties#7]
- Function of Front-End 
  - Structure
  - Classes
- Programming Languages
- Data Dictionary
- ERM

https://www.dropbox.com/scl/fi/wozo4fjerttgtl4lvx8zt/Proper-Properties.docx?dl=0&rlkey=ji6q7ap3bdv212qb37vkzjkqu

**Comment by DavidLeDuy** [comment]
ERM muss noch durch das neue ausgetauscht werden
